// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: syncer.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Action int32

const (
	// Common
	Action_Del      Action = 0
	Action_Expire   Action = 1
	Action_ExpireAt Action = 2
	Action_Persist  Action = 3
	// String
	Action_Set   Action = 21
	Action_SetNX Action = 22
	// Hash
	Action_HDel   Action = 40
	Action_HSet   Action = 41
	Action_HSetNx Action = 42
	// List
	Action_LPush  Action = 60
	Action_LPop   Action = 61
	Action_LShift Action = 62
	Action_LTrim  Action = 63
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "Del",
		1:  "Expire",
		2:  "ExpireAt",
		3:  "Persist",
		21: "Set",
		22: "SetNX",
		40: "HDel",
		41: "HSet",
		42: "HSetNx",
		60: "LPush",
		61: "LPop",
		62: "LShift",
		63: "LTrim",
	}
	Action_value = map[string]int32{
		"Del":      0,
		"Expire":   1,
		"ExpireAt": 2,
		"Persist":  3,
		"Set":      21,
		"SetNX":    22,
		"HDel":     40,
		"HSet":     41,
		"HSetNx":   42,
		"LPush":    60,
		"LPop":     61,
		"LShift":   62,
		"LTrim":    63,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_syncer_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_syncer_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{0}
}

// RunRequest 执行请求参数
type SyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action   `protobuf:"varint,1,opt,name=action,proto3,enum=proto.Action" json:"action,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_Del
}

func (x *SyncRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// RunResponse 执行返回参数
type SyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_syncer_proto protoreflect.FileDescriptor

var file_syncer_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x98, 0x01, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x41, 0x74, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x10, 0x15, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x65, 0x74, 0x4e, 0x58, 0x10, 0x16, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x44, 0x65, 0x6c,
	0x10, 0x28, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x53, 0x65, 0x74, 0x10, 0x29, 0x12, 0x0a, 0x0a, 0x06,
	0x48, 0x53, 0x65, 0x74, 0x4e, 0x78, 0x10, 0x2a, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x50, 0x75, 0x73,
	0x68, 0x10, 0x3c, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x50, 0x6f, 0x70, 0x10, 0x3d, 0x12, 0x0a, 0x0a,
	0x06, 0x4c, 0x53, 0x68, 0x69, 0x66, 0x74, 0x10, 0x3e, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x54, 0x72,
	0x69, 0x6d, 0x10, 0x3f, 0x32, 0x71, 0x0a, 0x06, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x32,
	0x0a, 0x05, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x33, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_syncer_proto_rawDescOnce sync.Once
	file_syncer_proto_rawDescData = file_syncer_proto_rawDesc
)

func file_syncer_proto_rawDescGZIP() []byte {
	file_syncer_proto_rawDescOnce.Do(func() {
		file_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(file_syncer_proto_rawDescData)
	})
	return file_syncer_proto_rawDescData
}

var file_syncer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_syncer_proto_goTypes = []interface{}{
	(Action)(0),          // 0: proto.Action
	(*SyncRequest)(nil),  // 1: proto.SyncRequest
	(*SyncResponse)(nil), // 2: proto.SyncResponse
}
var file_syncer_proto_depIdxs = []int32{
	0, // 0: proto.SyncRequest.action:type_name -> proto.Action
	1, // 1: proto.Syncer.Slave:input_type -> proto.SyncRequest
	1, // 2: proto.Syncer.Master:input_type -> proto.SyncRequest
	2, // 3: proto.Syncer.Slave:output_type -> proto.SyncResponse
	2, // 4: proto.Syncer.Master:output_type -> proto.SyncResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_syncer_proto_init() }
func file_syncer_proto_init() {
	if File_syncer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_syncer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syncer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syncer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncer_proto_goTypes,
		DependencyIndexes: file_syncer_proto_depIdxs,
		EnumInfos:         file_syncer_proto_enumTypes,
		MessageInfos:      file_syncer_proto_msgTypes,
	}.Build()
	File_syncer_proto = out.File
	file_syncer_proto_rawDesc = nil
	file_syncer_proto_goTypes = nil
	file_syncer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SyncerClient is the client API for Syncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncerClient interface {
	Slave(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	Master(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type syncerClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncerClient(cc grpc.ClientConnInterface) SyncerClient {
	return &syncerClient{cc}
}

func (c *syncerClient) Slave(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/proto.Syncer/Slave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncerClient) Master(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/proto.Syncer/Master", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncerServer is the server API for Syncer service.
type SyncerServer interface {
	Slave(context.Context, *SyncRequest) (*SyncResponse, error)
	Master(context.Context, *SyncRequest) (*SyncResponse, error)
}

// UnimplementedSyncerServer can be embedded to have forward compatible implementations.
type UnimplementedSyncerServer struct {
}

func (*UnimplementedSyncerServer) Slave(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Slave not implemented")
}
func (*UnimplementedSyncerServer) Master(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Master not implemented")
}

func RegisterSyncerServer(s *grpc.Server, srv SyncerServer) {
	s.RegisterService(&_Syncer_serviceDesc, srv)
}

func _Syncer_Slave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).Slave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Syncer/Slave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).Slave(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Syncer_Master_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncerServer).Master(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Syncer/Master",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncerServer).Master(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Syncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Syncer",
	HandlerType: (*SyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Slave",
			Handler:    _Syncer_Slave_Handler,
		},
		{
			MethodName: "Master",
			Handler:    _Syncer_Master_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncer.proto",
}
